// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSdlGuhkqUmeV9C0s2OC5zpWAAgCLE1UY',
    appId: '1:616730303962:web:fcd86aff538ed54f3434e3',
    messagingSenderId: '616730303962',
    projectId: 'pertemuan-10-e1ace',
    authDomain: 'pertemuan-10-e1ace.firebaseapp.com',
    storageBucket: 'pertemuan-10-e1ace.firebasestorage.app',
    measurementId: 'G-V0XF9Z603Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHeoXwMwVX4CE-CgOxTGo0yjsL4nmopBA',
    appId: '1:616730303962:android:f5b642fc0f2d4b813434e3',
    messagingSenderId: '616730303962',
    projectId: 'pertemuan-10-e1ace',
    storageBucket: 'pertemuan-10-e1ace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPhv7Dfffh2wL5BZM4RdEdf5rSuwmwKOI',
    appId: '1:616730303962:ios:fd1e6036ee8592ae3434e3',
    messagingSenderId: '616730303962',
    projectId: 'pertemuan-10-e1ace',
    storageBucket: 'pertemuan-10-e1ace.firebasestorage.app',
    iosBundleId: 'com.example.pemprogramanMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPhv7Dfffh2wL5BZM4RdEdf5rSuwmwKOI',
    appId: '1:616730303962:ios:fd1e6036ee8592ae3434e3',
    messagingSenderId: '616730303962',
    projectId: 'pertemuan-10-e1ace',
    storageBucket: 'pertemuan-10-e1ace.firebasestorage.app',
    iosBundleId: 'com.example.pemprogramanMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSdlGuhkqUmeV9C0s2OC5zpWAAgCLE1UY',
    appId: '1:616730303962:web:72f1d6478a6ee1b43434e3',
    messagingSenderId: '616730303962',
    projectId: 'pertemuan-10-e1ace',
    authDomain: 'pertemuan-10-e1ace.firebaseapp.com',
    storageBucket: 'pertemuan-10-e1ace.firebasestorage.app',
    measurementId: 'G-HT9P8H41P1',
  );
}
